# Generated by Django 3.1.4 on 2020-12-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restart_group', models.BooleanField()),
                ('message_group', models.CharField(max_length=30)),
                ('mturk_id', models.CharField(max_length=30)),
                ('hash_id', models.CharField(max_length=30)),
                ('install_date', models.DateTimeField()),
                ('windows_version', models.CharField(max_length=50)),
                ('dot_net_version', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('response', models.CharField(max_length=20)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.participant')),
            ],
        ),
    ]
