# Generated by Django 3.1.4 on 2020-12-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20201214_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='noti_date',
        ),
    ]
