# Generated by Django 3.1.4 on 2021-01-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_auto_20201214_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='hash_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mturk_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='restart_group',
            field=models.CharField(max_length=30),
        ),
    ]
