# Generated by Django 3.1.4 on 2021-01-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_auto_20210103_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hash_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mturk_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sequence',
            field=models.CharField(max_length=5),
        ),
    ]
