# Generated by Django 3.1.4 on 2021-08-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_auto_20210104_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_id', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=30)),
                ('ping_date', models.DateTimeField()),
            ],
        ),
    ]
